services:
  jenkins:
    container_name: Jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home:z
  tomcat:
    container_name: Tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - '4287:4287'
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs:z
    env_file:
      - './tomcat/compose.env'
  ansible:
    container_name: Ansible
    hostname: ansible-server
    privileged: true
    build:
      context: ./ansible
      dockerfile: Dockerfile
    ports:
      - '5200:5200'
    volumes:
      - ./ansible/data:/home/ansadmin:z
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg:z
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./ansible/hosts:/etc/ansible/hosts:z
      - ./ansible/tomcat:/tomcat:z
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
      - ANSIBLE_CONFIG=/etc/ansible/ansible.cfg
  registry:
    container_name: Registry
    image: docker.io/library/registry:3
    ports:
      - '7001:7001'
      - '5000:5000'
    volumes:
      - ./registry/data:/var/lib/registry:z
      - ./registry/htpasswd:/etc/docker/registry/htpasswd:z
      - ./registry/certs:/certs:z
      - ./registry/daemon.json:/etc/docker/daemon.json:z
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /etc/docker/registry/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: var/lib/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_SECRET: Ntopor2024
    restart: always
volumes:
  jenkins_home:
  tomcat_logs:
  ansible_data:
